apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    app: itop
  name: itop
spec:
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: itop:latest
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    git:
      ref: develop
      uri: https://github.com/pittar/iTop.git
    type: Git
  strategy:
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: php-s2i-72-graphviz:latest
    type: Source
  triggers:
  - imageChange: {}
    type: ImageChange
  - type: ConfigChange
